---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websockets-demo
  labels:
    app: websockets-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websockets-demo
  template:
    metadata:
      labels:
        app: websockets-demo
    spec:
      containers:
      - name: websockets-demo
        image: quay.io/tomastomecek/websockets-demo:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: websockets-demo
spec:
  selector:
    app: websockets-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: websockets-demo
spec:
  port:
    targetPort: 8081
  to:
    kind: Service
    name: websockets-demo
    weight: 100
